spring: 
  application:
    name: eureka-zuul
server:
  port: 8761
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
zuul:
  ignoredServices: '*'
  prefix: /api
  retryable: true
  strip-prefix: false
  routes: 
    movies: 
      path: /moviesservice/**
      serviceId: movies-service
    catalog: 
      path: /catalogservice/**
      url: http://localhost:8081